import { test, expect } from '@playwright/test';

test('UVA Analysis Full Flow', async ({ page, request }) => {
    const timestamp = new Date().getTime();
    const random = Math.floor(Math.random() * 10000);
    const username = `user_${timestamp}_${random}`;
    const password = 'ROI_Demo_2026!';

    // 1. Register new user via API
    const regResponse = await request.post('/api/auth/register', {
        data: {
            username,
            password,
            displayName: `Test User ${timestamp} `
        }
    });
    expect(regResponse.ok()).toBeTruthy();

    // 2. Enter Dashboard (will redirect to login)
    await page.goto('/');

    // Always login since it's a fresh context
    await page.getByPlaceholder('输入您的用户名').fill(username);
    await page.getByPlaceholder('输入您的密码').fill(password);
    await page.getByRole('button', { name: '登录' }).click();

    // Wait for login to complete and redirect SANS refresh
    // This asserts Bug 1 is fixed (Login Refresh)
    await expect(page.locator('.navbar-brand')).toBeVisible();
    await expect(page.locator('.user-name')).toBeVisible(); // Check user name immediately

    // ... create project ...

    // 3. Create a new project for testing
    await page.getByText('新建方案').click();
    await expect(page.locator('.modal-overlay')).toBeVisible(); // Ensure modal is open

    const projectTimestamp = new Date().getTime();
    const projectName = `E2E Test ${projectTimestamp} `;
    // Scope to modal
    await page.locator('.modal-content input[type="text"]').fill(projectName);
    await page.locator('.modal-content textarea').fill('Auto-generated by Playwright');

    // Select Vehicles (Leo is usually first or explicitly select)
    await page.locator('.modal-body input[type="checkbox"]').first().check();

    // Simplified: just click create since vehicles are auto-selected or default
    await page.locator('.modal-footer button[type="submit"]').click();

    // Check for error message if modal doesn't close
    try {
        await expect(page.locator('.modal-overlay')).not.toBeVisible({ timeout: 5000 });
    } catch (e) {
        // If modal is still visible, check for error
        if (await page.locator('.error-message').isVisible()) {
            const error = await page.locator('.error-message').textContent();
            console.error(`Create Project Failed: ${error}`);
            throw new Error(`Create Project Failed: ${error}`);
        }
        throw e;
    }

    // 3. Enter Project Detail
    // Optimization: Auto-navigates now, so we just wait for the title
    // await page.getByText(projectName).click(); // Removed manual click
    // Wait for navigation
    await expect(page.locator('h1')).toHaveText(projectName);

    // 4. Enhanced Mode Selection
    // Select "智能驾驶" (Assuming it's in the list)
    await page.getByText('智能驾驶').click();
    // Check the first UV item
    await page.locator('.uv-l2-checkbox').first().check();

    // 5. Reduced Mode Selection & Feedback Check
    // This asserts Bug 3 is fixed (Minus Mode Feedback)
    const minusBtn = page.getByRole('button', { name: '减弱 (-)' });
    await minusBtn.click();
    // await expect(minusBtn).toHaveClass(/active/); // Button uses dynamic tailwind classes, not 'active'
    await expect(page.locator('.uv-data-section')).toHaveClass(/mode-reduced/); // Check section theme

    // Select another category
    await page.getByText('外观设计及车身外部功能件').click();
    // Check first UV item
    await page.locator('.uv-l2-checkbox').first().check();

    // 6. Calculate
    await page.getByRole('button', { name: '测算' }).click();

    // Verify Result Card Appears
    await expect(page.getByText('UVA 测算结果')).toBeVisible();
    // await expect(page.getByText('总分')).toBeVisible(); 

    // 7. Save
    // Mock dialog before clicking save
    page.on('dialog', async dialog => {
        console.log(`Dialog message: ${dialog.message()} `);
        await dialog.accept();
    });
    await page.getByRole('button', { name: '保存' }).click();

    // Wait a bit to ensure save completes (in real test we should wait for response or UI change)
    await page.waitForTimeout(1000);
});
