import { test, expect } from '@playwright/test';

test('UVA Analysis Full Flow', async ({ page, request }) => {
    const timestamp = new Date().getTime();
    const random = Math.floor(Math.random() * 10000);
    const username = `user_${timestamp}_${random}`;
    const password = 'ROI_Demo_2026!';

    // 1. Register new user via API
    const regResponse = await request.post('/api/auth/register', {
        data: {
            username,
            password,
            displayName: `Test User ${timestamp} `
        }
    });
    expect(regResponse.ok()).toBeTruthy();

    // 2. Enter Dashboard (will redirect to login)
    await page.goto('/');

    // Always login since it's a fresh context
    await page.getByPlaceholder('输入您的用户名').fill(username);
    await page.getByPlaceholder('输入您的密码').fill(password);
    await page.getByRole('button', { name: '登录' }).click();

    // Wait for dashboard page after successful login
    await expect(page.getByRole('heading', { name: '项目工作台' })).toBeVisible();

    // 3. Create a new project for testing
    await page.getByRole('button', { name: '新建项目' }).click();
    await expect(page.getByRole('heading', { name: '新建分析项目' })).toBeVisible();

    const projectTimestamp = new Date().getTime();
    const projectName = `E2E Test ${projectTimestamp} `;
    await page.getByPlaceholder('例如：2024 Q1 智能座舱优化').fill(projectName);
    await page.getByPlaceholder('简要描述背景和目标...').fill('Auto-generated by Playwright');

    // Select one vehicle
    await page.getByText('Leo', { exact: true }).click();

    await page.getByRole('button', { name: '创建项目' }).click();

    // Modal closes and project appears in grid
    await expect(page.getByRole('heading', { name: '新建分析项目' })).not.toBeVisible({ timeout: 5000 });
    await expect(page.getByText(projectName, { exact: true })).toBeVisible();

    // 3. Enter Project Detail
    await page.getByText(projectName, { exact: true }).click();
    await expect(page.locator('h1')).toHaveText(projectName);
    await expect(page.getByText('UVA 测算结果')).toBeVisible();

    // 4. Calculate (smoke)
    await page.getByRole('button', { name: '测算' }).click();
    await expect(page.getByText('UVA 测算结果')).toBeVisible();

    // 5. Save
    // Mock dialog before clicking save
    page.on('dialog', async dialog => {
        console.log(`Dialog message: ${dialog.message()} `);
        await dialog.accept();
    });
    await page.getByRole('button', { name: '保存' }).click();

    // Wait a bit to ensure save completes (in real test we should wait for response or UI change)
    await page.waitForTimeout(1000);
});
